apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: health-103
  description: test description
  annotations:
    argocd/app-name: health-103-dev
    tektonci/build-namespace: health-103-develop
    backstage.io/kubernetes-id: health-103
    janus-idp.io/tekton-enabled : 'true'
    janus-idp.io/tekton : health-103
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: skitamura-org/health-103-app
spec:
  type: service 
  system: "system:default/sample-system"
  lifecycle: production
  owner: "user:default/skitamura7446"
  git: github
  git_host_url: github.com
  git_owner_name: skitamura-org
